apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
type: Opaque
data:
  NODE_LOCAL_PORT: MzAwMA==  
  TOKEN_SECRET_KEY: NzNES2Y4dHROZHlCcVZDQnl2d3VXQ2I4NEpLTUVz  
  REDIS_HOST: cmVkaXMtZGF0YWJhc2UuZWt6MHluLm5nLjAwMDEudXNlMS5jYWNoZS5hbWF6b25hd3MuY29t
  REDIS_DOCKER_PORT: NjM3OQ==  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-tokenization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-card-tokenization
  template:
    metadata:
      labels:
        app: credit-card-tokenization
    spec:
      containers:
        - name: credit-card-tokenization
          image: 510391598264.dkr.ecr.us-east-1.amazonaws.com/credit-card-tokenization:latest
          imagePullPolicy: Always
          env:
            - name: NODE_LOCAL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: NODE_LOCAL_PORT
            - name: TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: TOKEN_SECRET_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: REDIS_HOST
            - name: REDIS_DOCKER_PORT
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: REDIS_DOCKER_PORT
          livenessProbe: 
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5