version: '3.8'

services:
  application:
    container_name: application
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis_database
    links:
      - redis_database
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  
  redis_database:
    container_name: redis_database
    image: redis
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT