apiVersion: v1
kind: Service
metadata:
  name: credit-card-tokenization-lb
spec:
  type: LoadBalancer
  selector:
    app: credit-card-tokenization
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31600
